// AUTO-GENERATED — TRUSTA landing copy. KO = verbatim user copy (line breaks preserved, do not alter).
export type Lang = "ko" | "en";
export interface Block { ko: string[]; en: string[]; }

export const blockOrder: string[] = ["b1_hero", "b2_translation", "b3_roles", "b4_compare", "b5_redocean", "b6_redesign", "b7_funnel", "b8_multichannel", "b9_search", "b10_landing", "b11_faq1", "b12_faq2", "b13_faq3", "b14_faq4", "b15_gate", "b16_calendar", "b17_improve", "b18_whofor", "b19_onesystem", "b20_packages", "b21_process", "b22_small", "b23_cta", "b24_closing"];

export const blocks: Record<string, Block> = {
  "b1_hero": { ko: ["해외로 더 넓은 시장에 진출할 기회,", "아직 제대로 잡지 못하고 계신가요?", "국내 광고는 점점 비싸지고", "SNS와 블로그는 이미 경쟁이 치열합니다.", "하지만 K-뷰티, 피부과, 성형외과, 치과,", "화장품 브랜드는 아직 해외 고객에게", "더 넓게 확장될 가능성이 있습니다.", "일본, 중국, 동남아, 미국, 유럽까지", "한국에서만 보던 고객이 아니라", "해외에서 검색하고, 비교하고, 문의하는 고객을", "만날 수 있는 시장입니다."], en: ["The chance to expand into wider markets overseas—", "are you still missing it?", "Domestic advertising keeps getting more expensive,", "and competition on social media and blogs is already fierce.", "But K-beauty, dermatology, plastic surgery, dental,", "and cosmetics brands still have room", "to reach far more customers abroad.", "Japan, China, Southeast Asia, the US, and Europe—", "not just the customers you've only met in Korea,", "but customers searching, comparing, and reaching out from overseas.", "These are the markets where you can meet them."] },
  "b2_translation": { ko: ["문제는 번역이 아닙니다.", "한국어 문장을 일본어로 바꿨다고", "일본 고객이 바로 이해하는 것은 아닙니다.", "영어로 번역했다고", "미국·유럽 고객이 신뢰하는 것도 아닙니다.", "현지 고객이 읽었을 때", "자연스럽게 이해되는 말투인지,", "이미지 톤이 그 나라 문화에 맞는지,", "효과를 과장하지 않으면서도", "믿을 수 있는 증거가 있는지,", "마지막에 문의와 상담으로 이어지는 흐름인지", "먼저 확인해야 합니다."], en: ["The challenge isn't translation.", "Turning a Korean sentence into Japanese", "doesn't mean Japanese customers will immediately understand it.", "Translating into English", "doesn't mean US and European customers will trust it.", "Whether it reads naturally", "when a local customer sees it,", "whether the image tone fits that country's culture,", "whether it has credible evidence", "without overstating results,", "and whether it leads to inquiries and consultations in the end—", "these need to be checked first."] },
  "b3_roles": { ko: ["요즘 넘쳐나는", "뻔한 해외 진출 대행 아닌가요?", "AI로 대충 번역하고", "이미지만 몇 장 만들어주는 서비스 아닌가요?", "현지화가 됐다고 하는데", "실제 문구 근거는 있는 건가요?", "광고법이나 의료·화장품 표현은", "정말 안전하게 점검되는 건가요?", "저희는 단순 제작이 아니라", "문구의 역할을 먼저 나눕니다.", "유지할 문장, 바꿔야 할 문장,", "삭제해야 할 문장, 증거가 필요한 문장,", "현지화가 필요한 문장을 구분합니다.", "그리고 국가별 말투, 이미지 톤,", "검색 키워드, 랜딩 흐름, 광고 표현 리스크까지", "다시 확인합니다."], en: ["Isn't this just another", "run-of-the-mill overseas-expansion agency?", "Isn't it a service that roughly translates with AI", "and just makes a few images?", "They say it's localized,", "but is there any actual basis for the copy?", "Are advertising laws and medical or cosmetics claims", "really checked safely?", "We don't just produce content—", "we first define the role of each line of copy.", "We separate lines to keep, lines to change,", "lines to delete, lines that need evidence,", "and lines that need localization.", "Then we recheck tone by country, image tone,", "search keywords, landing flow, and ad-claim risk—", "all over again."] },
  "b4_compare": { ko: ["과장 아니냐고요?", "그래서 결과물만 보여드리지 않습니다.", "한국형 문구와 일본형 문구의 차이,", "중국식 신뢰 구조와 동남아식 이미지 톤,", "영어권 고객이 선호하는 설명 방식까지", "비교해서 보여드립니다.", "번역 전 문장, 현지화 후 문장,", "수정 이유, 표현 리스크, 대체 문구를", "함께 정리합니다."], en: ["Think that's an overstatement?", "That's why we don't just show you the final result.", "The difference between Korean-style and Japanese-style copy,", "Chinese-style trust structures and Southeast Asian image tones,", "and the way English-speaking customers prefer explanations—", "we show you the comparison.", "The sentence before translation, the sentence after localization,", "the reason for the change, the claim risk, and the alternative copy—", "we lay it all out together."] },
  "b5_redocean": { ko: ["국내 SNS만으로는 이미 레드오션입니다.", "인스타그램은 매일 새로운 병원과 브랜드가 올라오고", "블로그는 광고성 글이 넘쳐나고", "키워드 광고 비용은 계속 올라갑니다.", "좋은 콘텐츠를 만들어도", "국내 고객에게만 보여주면", "성장 폭은 금방 막힐 수 있습니다."], en: ["Domestic social media alone is already a red ocean.", "New clinics and brands appear on Instagram every day,", "blogs are flooded with promotional posts,", "and keyword ad costs keep rising.", "Even if you create great content,", "showing it only to domestic customers", "can quickly cap your growth."] },
  "b6_redesign": { ko: ["지금 필요한 것은", "더 많이 올리는 것이 아닙니다.", "더 넓은 시장에 맞게", "다르게 설계하는 것입니다.", "한국에서 통하던 상세페이지를", "일본 고객용 랜딩으로 바꾸고,", "한국식 전후사진 중심 콘텐츠를", "중국·동남아 고객이 신뢰하는 흐름으로 바꾸고,", "국내 SNS 카드뉴스를", "해외 고객이 저장하고 문의할 수 있는 구조로 바꿔야 합니다."], en: ["What you need now", "isn't to post more.", "It's to design differently", "to fit a wider market.", "Turn a detail page that worked in Korea", "into a landing page made for Japanese customers,", "turn Korean-style before-and-after content", "into a flow that Chinese and Southeast Asian customers trust,", "and turn domestic social card news", "into a structure overseas customers can save and inquire about."] },
  "b7_funnel": { ko: ["K-뷰티, 피부과, 성형외과, 치과, 화장품은", "해외 고객이 이미 관심을 갖는 분야입니다.", "하지만 관심이 있다고", "바로 문의가 생기는 것은 아닙니다.", "처음 보는 브랜드를 믿을 수 있어야 하고", "시술과 제품 설명이 이해되어야 하고", "전후 변화, 후기, 인증, 과정, FAQ가", "안전하게 배치되어야 합니다.", "그래야 콘텐츠 노출이", "랜딩 유입으로 이어지고,", "랜딩 유입이", "문의와 상담으로 이어지고,", "상담이 예약과 재방문으로 이어집니다."], en: ["K-beauty, dermatology, plastic surgery, dental, and cosmetics", "are fields overseas customers are already interested in.", "But interest", "doesn't immediately turn into inquiries.", "A first-time brand has to feel trustworthy,", "the procedures and product details have to make sense,", "and before-and-after changes, reviews, certifications, the process, and FAQs", "have to be placed safely.", "Only then does content exposure", "lead to landing-page visits,", "landing-page visits", "lead to inquiries and consultations,", "and consultations lead to bookings and return visits."] },
  "b8_multichannel": { ko: ["TRUSTA는 이 흐름을", "콘텐츠 하나에서 끝내지 않습니다.", "해외 진출 콘텐츠 전략부터", "국가별 현지화 콘텐츠 제작,", "현지화 이미지 제작,", "SNS 카드뉴스와 캐러셀 제작,", "Instagram, Facebook, Threads, X, 블로그까지", "하나의 핵심 콘텐츠를 여러 채널로 확산합니다."], en: ["TRUSTA doesn't end this flow", "with a single piece of content.", "From overseas-expansion content strategy", "to localized content production by country,", "localized image production,", "social card news and carousel production,", "and on to Instagram, Facebook, Threads, X, and blogs—", "we spread one core piece of content across multiple channels."] },
  "b9_search": { ko: ["검색도 함께 봅니다.", "해외 고객은 SNS만 보지 않습니다.", "검색하고, 비교하고, 질문하고,", "AI 검색 결과에서 다시 확인합니다.", "그래서 블로그, SEO, AEO, GEO 콘텐츠까지", "함께 설계합니다.", "검색 키워드에서 블로그로,", "블로그에서 랜딩페이지로,", "랜딩페이지에서 문의로 이어지는 구조를 만듭니다."], en: ["We look at search, too.", "Overseas customers don't only look at social media.", "They search, compare, ask questions,", "and double-check through AI search results.", "So we also design blog, SEO, AEO, and GEO content", "together.", "From search keywords to the blog,", "from the blog to the landing page,", "from the landing page to the inquiry—we build that structure."] },
  "b10_landing": { ko: ["상세페이지와 랜딩페이지도", "그냥 예쁘게 만들지 않습니다.", "어떤 고객이 들어오는지,", "어떤 의심을 먼저 해결해야 하는지,", "어떤 증거를 어디에 배치해야 하는지,", "문의 버튼을 언제 보여줘야 하는지까지", "흐름으로 재구성합니다."], en: ["We don't just make detail pages and landing pages", "look pretty.", "Which customers are coming in,", "which doubts need to be addressed first,", "which evidence belongs where,", "and when to show the inquiry button—", "we rebuild it all as a flow."] },
  "b11_faq1": { ko: ["Q. 현지어를 잘 몰라도 가능한가요?", "가능합니다.", "단, 감으로 번역하면 안 됩니다.", "한국어 원문을 그대로 옮기는 것이 아니라", "일본식, 중국식, 동남아식, 영어권식 표현으로", "다시 설계해야 합니다.", "번역투 문장을", "현지 고객이 읽는 자연스러운 문장으로 바꾸고,", "이미지 톤도", "한국 느낌, 일본 느낌, 인도 느낌,", "동남아 느낌, 미국·유럽 느낌으로 나눠 제작합니다."], en: ["Q. Is it possible even if I don't know the local language well?", "Yes, it is.", "But you can't translate by gut feeling.", "Rather than carrying the Korean original over as is,", "it has to be redesigned into Japanese, Chinese, Southeast Asian, and English-speaking phrasing.", "Translationese sentences", "are turned into sentences that read naturally to local customers,", "and image tone", "is produced separately for a Korean feel, a Japanese feel, an Indian feel,", "a Southeast Asian feel, and a US/European feel."] },
  "b12_faq2": { ko: ["Q. 기존 자료가 없어도 가능한가요?", "가능합니다.", "다만 아무 자료 없이", "멋진 말만 만드는 방식은 하지 않습니다.", "브랜드 소개, 제품 정보, 시술 과정,", "후기, 사진, 인증, 가격, 자주 묻는 질문을 받아", "콘텐츠 구조를 먼저 잡습니다.", "자료가 부족한 경우에는", "어떤 증거가 더 필요한지도 함께 정리합니다."], en: ["Q. Is it possible even without existing materials?", "Yes, it is.", "But we don't take an approach", "of making nice-sounding words with no materials at all.", "We take in your brand introduction, product information, procedure process,", "reviews, photos, certifications, prices, and frequently asked questions", "to set the content structure first.", "When materials are lacking,", "we also lay out what additional evidence is needed."] },
  "b13_faq3": { ko: ["Q. 의료광고나 화장품 표현도 볼 수 있나요?", "1차 검수로 확인합니다.", "효과를 보장하는 문장,", "과장으로 보일 수 있는 문장,", "오해를 만들 수 있는 문장,", "국가별로 조심해야 할 표현을 점검합니다.", "위험 문구는 그대로 두지 않고", "안전한 대체 문구로 바꿔 제안합니다."], en: ["Q. Can you review medical-advertising or cosmetics claims, too?", "We check them in a first-pass review.", "Sentences that guarantee results,", "sentences that could look exaggerated,", "sentences that could create misunderstanding,", "and expressions to be careful with by country—we examine them.", "We don't leave risky copy as is;", "we propose safe alternative wording instead."] },
  "b14_faq4": { ko: ["Q. 일반 AI 콘텐츠와 뭐가 다른가요?", "일반 AI는 빠르게 문장을 만듭니다.", "하지만 빠른 문장이", "바로 발행 가능한 문장은 아닙니다.", "TRUSTA는 Graphify 기반으로", "문구를 다시 검증합니다.", "근거가 있는지, 출처가 필요한지,", "광고법 리스크가 있는지,", "현지화 기준에 맞는지,", "문의 전환 흐름이 살아있는지 다시 봅니다."], en: ["Q. How is this different from ordinary AI content?", "Ordinary AI produces sentences quickly.", "But a quick sentence", "isn't a sentence that's ready to publish.", "TRUSTA re-verifies the copy", "based on Graphify.", "Whether there's a basis, whether a source is needed,", "whether there's advertising-law risk,", "whether it meets localization standards,", "and whether the inquiry-conversion flow is intact—we look again."] },
  "b15_gate": { ko: ["그리고 AI가 만든 콘텐츠를", "바로 발행하지 않습니다.", "사람 검수 게이트를 둡니다.", "승인, 보류, 수정 요청을 거쳐", "발행 전 마지막 확인이 가능하도록 운영합니다."], en: ["And we don't publish AI-created content", "right away.", "We place a human review gate.", "Through approval, hold, and revision requests,", "we run a final check before publishing."] },
  "b16_calendar": { ko: ["한 달 운영도 가능합니다.", "이번 달 어떤 SNS 주제를 올릴지,", "카드뉴스는 몇 개가 필요한지,", "릴스와 블로그는 어떤 흐름으로 갈지,", "광고 소재는 무엇을 테스트할지", "월간 콘텐츠 캘린더로 정리합니다."], en: ["Monthly operation is available, too.", "Which social topics to post this month,", "how many card-news pieces are needed,", "what flow the reels and blog should follow,", "and which ad creatives to test—", "we organize it all in a monthly content calendar."] },
  "b17_improve": { ko: ["콘텐츠는 올리는 것보다", "개선하는 것이 더 중요합니다.", "조회, 저장, 클릭, 문의, 상담, 예약 데이터를 보고", "다음 콘텐츠 방향을 다시 제안합니다.", "어떤 문구가 저장을 만들었는지,", "어떤 랜딩이 문의를 만들었는지,", "어떤 이미지가 이탈을 줄였는지", "성과 리포트로 확인합니다."], en: ["With content, improving it", "matters more than posting it.", "We look at views, saves, clicks, inquiries, consultations, and booking data", "and re-propose the direction for the next content.", "Which copy drove saves,", "which landing page drove inquiries,", "and which image reduced drop-off—", "we confirm it in a performance report."] },
  "b18_whofor": { ko: ["이런 분들은 꼭 확인해보세요.", "국내 광고비가 부담되는 병원", "해외 고객 문의를 받고 싶지만", "어디서부터 시작해야 할지 모르는 브랜드", "일본, 중국, 동남아, 미국, 유럽 고객에게", "맞는 말투와 이미지가 필요한 업체", "AI로 콘텐츠를 만들고 있지만", "광고법과 현지화가 불안한 팀", "SNS, 블로그, 랜딩, 리포트가", "따로 움직여서 성과가 끊기는 곳", "해외 진출은 하고 싶은데", "전담 마케팅 인력을 두기 어려운 곳"], en: ["If this sounds like you, take a look.", "Clinics burdened by domestic ad costs.", "Brands that want overseas customer inquiries", "but don't know where to start.", "Businesses that need the right tone and images", "for customers in Japan, China, Southeast Asia, the US, and Europe.", "Teams creating content with AI", "but uneasy about advertising law and localization.", "Places where social, blog, landing, and reporting", "move separately, breaking the results.", "Places that want to expand overseas", "but find it hard to keep a dedicated marketing team."] },
  "b19_onesystem": { ko: ["혼자 여러 업체를 관리하지 않아도 됩니다.", "콘텐츠 전략, 현지화, 이미지 제작,", "SNS 카드뉴스, 멀티 SNS 확산,", "블로그·SEO·AEO·GEO 콘텐츠,", "상세페이지와 랜딩페이지,", "광고법·의료·화장품 표현 1차 검수,", "현지화 말투 검수, 사람 검수 게이트,", "성과 리포트와 개선 제안까지", "하나의 시스템으로 연결합니다."], en: ["You don't have to manage multiple vendors on your own.", "Content strategy, localization, image production,", "social card news, multi-platform social distribution,", "blog, SEO, AEO, and GEO content,", "detail pages and landing pages,", "first-pass review of advertising-law, medical, and cosmetics claims,", "localized-tone review, the human review gate,", "and performance reports with improvement suggestions—", "we connect it all into one system."] },
  "b20_packages": { ko: ["Starter는", "해외 진출을 처음 준비하는 브랜드를 위한 구성입니다.", "Growth는", "SNS와 랜딩, 검색 콘텐츠를 함께 키우는 구성입니다.", "Premium은", "월간 운영, 검수, 리포트, 개선까지", "지속적으로 관리하는 구성입니다."], en: ["Starter", "is built for brands preparing to expand overseas for the first time.", "Growth", "is built to grow social, landing, and search content together.", "Premium", "is built to continuously manage monthly operation, review,", "reporting, and improvement."] },
  "b21_process": { ko: ["진행 방식은 간단합니다.", "먼저 기존 자료를 전달합니다.", "홈페이지, 상세페이지, SNS, 블로그,", "제품 정보, 시술 정보, 사진, 후기, FAQ를 확인합니다.", "그다음 국가와 고객을 정합니다.", "일본 고객인지, 중국 고객인지,", "동남아 고객인지, 영어권 고객인지에 따라", "문구와 이미지 방향을 다르게 설계합니다.", "그 후 콘텐츠를 재구성합니다.", "문장 흐름을 바꾸고,", "증거를 배치하고,", "위험 표현을 점검하고,", "SNS와 랜딩, 검색 콘텐츠로 나눕니다.", "마지막으로 검수 후 납품합니다.", "발행 가능한 콘텐츠, 수정 이유,", "전후 비교, 운영 캘린더, 성과 리포트 기준까지", "확인할 수 있게 정리합니다."], en: ["The process is simple.", "First, you share your existing materials.", "We review your website, detail pages, social, blog,", "product information, procedure information, photos, reviews, and FAQs.", "Next, we define the country and the customer.", "Depending on whether they're Japanese, Chinese,", "Southeast Asian, or English-speaking customers,", "we design the copy and image direction differently.", "Then we rebuild the content.", "We change the sentence flow,", "place the evidence,", "check risky expressions,", "and split it into social, landing, and search content.", "Finally, we review and deliver.", "Publish-ready content, the reasons for changes,", "before-and-after comparisons, the operation calendar, and performance-report criteria—", "we organize it all so you can review it."] },
  "b22_small": { ko: ["해외 진출은", "큰 회사만 하는 일이 아닙니다.", "작은 병원도, 작은 브랜드도", "처음부터 거창한 지사를 만들 필요는 없습니다.", "먼저 콘텐츠를 바꾸고", "문구를 바꾸고", "랜딩 흐름을 바꾸면 됩니다.", "해외 고객이 이해하고", "신뢰하고", "문의할 수 있는 구조부터 만들면 됩니다."], en: ["Expanding overseas", "isn't only for big companies.", "Small clinics and small brands", "don't need to build a grand overseas office from the start.", "First, change the content,", "change the copy,", "and change the landing flow.", "Just start with a structure where overseas customers", "understand it,", "trust it,", "and can reach out."] },
  "b23_cta": { ko: ["국내 시장이 좁게 느껴진다면,", "광고비는 오르는데", "문의가 늘지 않는다면,", "해외 고객에게 보여줄 콘텐츠가 있지만", "번역과 현지화가 불안하다면,", "AI로 만든 문구를 바로 쓰기 어렵다면,", "이제 해외 진출 전", "문구와 콘텐츠 흐름부터 먼저 점검하세요.", "콘텐츠 노출에서", "랜딩 유입,", "문의와 상담,", "예약과 재방문,", "그리고 성과 분석과 개선까지.", "TRUSTA 검증형 AI 콘텐츠 운영으로", "해외 고객에게 통하는 콘텐츠 구조를 만듭니다."], en: ["If the domestic market feels narrow,", "if ad costs keep rising", "but inquiries aren't growing,", "if you have content to show overseas customers", "but you're uneasy about translation and localization,", "if it's hard to use AI-made copy as is,", "then before expanding overseas,", "check your copy and content flow first.", "From content exposure", "to landing-page visits,", "to inquiries and consultations,", "to bookings and return visits,", "and on to performance analysis and improvement.", "With TRUSTA's verified AI content operation,", "we build a content structure that resonates with overseas customers."] },
  "b24_closing": { ko: ["지금 가지고 있는 한국어 콘텐츠를", "해외 고객이 이해하고 신뢰하는 콘텐츠로 바꿔보세요.", "해외 진출은", "번역이 아니라 흐름입니다.", "그리고 그 흐름은", "첫 문장부터 달라져야 합니다."], en: ["Take the Korean content you have now", "and turn it into content overseas customers understand and trust.", "Expanding overseas", "is about flow, not translation.", "And that flow", "has to be different from the very first sentence."] },
};

export const ui = {
  ko: {
    nav: { home: "홈", proof: "신뢰 철학", services: "서비스 흐름", process: "운영·프로세스", packages: "패키지", faq: "FAQ", contact: "문의" },
    brand: { name: "TRUSTA", sub: "글로벌 콘텐츠 & 흐름 OS" },
    badge: "해외 진출 검증형 콘텐츠 운영팀",
    cta: "무료 진단",
    primary: "무료 진단 요청",
    secondary: "서비스 살펴보기",
    sectionLabels: {
      proof: "01 / 신뢰 철학", risk: "02 / 표현 리스크", reality: "03 / 시장 현실",
      services: "04 / 시스템 흐름", search: "05 / 검색 설계", faq: "06 / 자주 묻는 질문",
      gate: "07 / 사람 검수 게이트", ops: "08 / 월간 운영", whofor: "09 / 이런 분들께",
      packages: "10 / 패키지", process: "11 / 진행 방식", closing: "12 / 마무리",
    },
    riskWidget: {
      title: "번역 전 문장 vs 현지화 후 문장",
      desc: "같은 소구점도 국가별 정서·심의 기준에 따라 안전성과 신뢰도를 함께 높이는 대체 표현 예시입니다.",
      tryLabel: "직접 문구를 입력해 보세요",
      placeholder: "예: 확실한 효과, 부작용 없음",
      check: "검사",
      result: "안전 대체 문구 예시",
      before: "위험 표현 (예시)",
      after: "안전 대체 (예시)",
    },
    calc: {
      eyebrow: "운영량 시뮬레이터",
      title: "월간 콘텐츠 운영량을 조절해 보세요",
      desc: "월간 필요한 콘텐츠·검수 분량을 움직여, 한 시스템으로 묶었을 때의 운영 부담을 가늠해 보세요.",
      min: "최소", max: "최대", unit: "개 / 월",
      out1: "월간 산출 콘텐츠", out2: "묶이는 채널", out2v: "SNS·블로그·랜딩·검색",
    },
    crm: { eyebrow: "운영 리포트 예시", title: "성과 데이터로 다음 콘텐츠를 다시 제안", live: "예시 리포트",
      foot: "모든 문의·성과가 하나의 리포트로 정리됩니다",
      tabs: ["조회·저장", "클릭·문의", "상담·예약", "개선 제안"] },
    contact: { email: "contact@trusta.global", formLabel: "이메일 주소", placeholder: "name@company.com", button: "무료 문구·흐름 진단 요청", sent: "진단 신청이 접수되었습니다" },
    footer: { brand: "TRUSTA GLOBAL", tagline: "국가별 현지화 콘텐츠 · 멀티 SNS 확산 · 상세·랜딩 흐름 설계 · 검색 최적화 OS", rights: "© 2026 TRUSTA GLOBAL. All rights reserved." },
    langSwitch: "🌐 Switch to EN",
  },
  en: {
    nav: { home: "Home", proof: "Philosophy", services: "Service Flow", process: "Operations", packages: "Packages", faq: "FAQ", contact: "Contact" },
    brand: { name: "TRUSTA", sub: "Global Content & Flow OS" },
    badge: "Verified Content Operations for Global Expansion",
    cta: "Free Audit",
    primary: "Request Free Audit",
    secondary: "Explore Services",
    sectionLabels: {
      proof: "01 / Philosophy", risk: "02 / Claim Risk", reality: "03 / Market Reality",
      services: "04 / System Flow", search: "05 / Search Design", faq: "06 / FAQ",
      gate: "07 / Human Gate", ops: "08 / Monthly Ops", whofor: "09 / Who It's For",
      packages: "10 / Packages", process: "11 / Process", closing: "12 / Closing",
    },
    riskWidget: {
      title: "Before-translation vs After-localization",
      desc: "An example of alternative wording that raises both safety and trust according to each country's sentiment and review standards.",
      tryLabel: "Try your own copy",
      placeholder: "e.g. guaranteed results, no side effects",
      check: "Check",
      result: "Safe alternative (example)",
      before: "Risky claim (example)",
      after: "Safe alternative (example)",
    },
    calc: {
      eyebrow: "Volume Simulator",
      title: "Adjust your monthly content volume",
      desc: "Move the monthly content/review volume to gauge the operating load when it's unified into one system.",
      min: "Min", max: "Max", unit: " / mo",
      out1: "Monthly content output", out2: "Channels unified", out2v: "Social · Blog · Landing · Search",
    },
    crm: { eyebrow: "Operations Report (example)", title: "Re-propose the next content from performance data", live: "Example report",
      foot: "Every inquiry and result is organized into one report",
      tabs: ["Views·Saves", "Clicks·Inquiry", "Consult·Book", "Suggestions"] },
    contact: { email: "contact@trusta.global", formLabel: "Email address", placeholder: "name@company.com", button: "Request Free Copy & Flow Audit", sent: "Your audit request has been received" },
    footer: { brand: "TRUSTA GLOBAL", tagline: "Country-specific localized content · Multi-channel SNS diffusion · Detail & landing flow design · Search optimization OS", rights: "© 2026 TRUSTA GLOBAL. All rights reserved." },
    langSwitch: "🌐 한국어로 변경",
  },
} as const;
