import { LanguageCopy } from "./types";

export const copyDataset: Record<"ko" | "en", LanguageCopy> = {
  ko: {
    nav: {
      home: "홈",
      proof: "증거",
      risk: "리스크",
      services: "서비스",
      process: "프로세스",
      packages: "패키지",
      faq: "FAQ",
      contact: "문의",
      cta: "무료 진단",
    },
    brand: {
      name: "TRUSTA",
      sub: "GLOBAL MEDICAL MARKETING OS",
    },
    hero: {
      badge: "해외환자 유치 실행팀",
      line1: "해외환자 유치",
      line2: "이제 감으로 하지 마세요",
      desc: "일본·중국·동남아 고객이 병원을 발견하고 문의하고 예약까지 이어지도록 다국어 SNS, 랜딩페이지, 챗봇 문의, 의료광고 문구 검수까지 병원 대신 구축하고 운영해드립니다.",
      primary: "무료 진단 요청",
      secondary: "해외환자 마케팅 실행 시스템",
      stat1: "50-100개",
      stat1Label: "월간 콘텐츠 운영량",
      stat2: "3단계 검수",
      stat2Label: "AI 초안 + 인간 최종 필터링",
      stat3: "원스톱 동선",
      stat3Label: "SNS에서 랜딩 및 챗봇 연동",
    },
    philosophy: {
      title: "해외환자 마케팅은 예쁜 번역이 아닙니다",
      desc: "단순히 어조 좋은 표현만 올리는 것으로는 해외 고객의 신뢰를 얻거나 광고 심의를 보장할 수 없습니다.",
      elements: [
        "외국인이 이해하는 자연스러운 문장",
        "플랫폼이 막지 않는 안전한 표현",
        "의료광고 리스크를 사전에 줄인 구조",
        "문의가 끊기지 않고 이어지는 최종 동선",
      ],
    },
    differentiation: {
      title: "번역만 해주는 다른 업체들과는 다릅니다",
      desc: "단순 노출 중심이 아닌, 실제 예약 문의로 골트인되게끔 하는 완결 구조 마케팅을 지향합니다.",
      cards: [
        "번역만 해주는 다른 번역 업체들과 다릅니다",
        "SNS 게시물만 단순 기계식으로 올려주는 운영 대행이 아닙니다",
        "랜딩페지만 일회성으로 예쁘게 그리는 일반 웹디자인 제작사도 아닙니다",
      ],
      highlight: "해외환자가 병원을 보고, 믿고, 즉각 문의할 수 있도록 콘텐츠 제작부터 최종 문의 동선 연결까지 한 번에 단단하게 잡아드립니다.",
    },
    copyRisk: {
      title: "해외환자 유치에서 가장 위험한 것은",
      desc: "광고를 아예 안 하는 것이 아니라, 잘못되고 불법 소지가 다분한 문구로 불안한 마케팅을 송출하는 것 자체입니다.",
      intro: "국내 의료법 및 각 플랫폼 광고 심의 규정을 반드시 지켜야 계정 정지와 제재를 피할 수 있습니다.",
      points: [
        "효과가 무조건 보장되는 것처럼 과장하는 표현",
        "객관성 없는 자의적인 전후사진 비교 홍보",
        "블랙마켓성 오용 환자 치료 후기 리뷰 무단 노출",
        "시술 결과를 터무니없이 확실하다고 단정하는 단어",
        "국가별 어법과 정서에 맞지 않는 조악한 번역기 말투",
      ],
      consequences: "이런 문장 단 한 줄이 광고 반려, 게시물 강제 삭제, 병원 공식 계정 영구 제한, 브랜드 신뢰도의 치명적 하락으로 다이렉트하게 직결됩니다.",
      titleBeforeAfter: "좋은 마케팅 문구는 화려한 수식어가 아닙니다",
      descBeforeAfter: "문제가 될 리스크는 최소화하고, 고객에게는 가장 설득력 있고 투명한 안전 대체 표현으로 치환하는 역량입니다.",
    },
    riskPairs: [
      {
        level: "위험 표현 (RED/BEFORE)",
        tone: "효과 단정형 광고 반려 1순위",
        title: "수정 전 : 확실히 고칠 수 있습니다",
        before: "“한 번의 시술로 확실한 극적 효과”",
        after: "“개인의 피부와 조직 상태에 따라 구체적 반응 및 결과는 달라질 수 있으며, 사전 내원 상담을 통해 가장 적합하고 정밀한 시술 방향을 디테일하게 안내해드립니다.”",
      },
      {
        level: "위험 표현 (YELLOW/BEFORE)",
        tone: "부작용 은폐 및 과장 오해 소지",
        title: "수정 전 : 절대 안전 / 부작용 무",
        before: "“부작용 없는 완벽하게 안전한 무사고 시술”",
        after: "“시술 전에 발생할 수 있는 붓기, 부종 등의 주의사항과 개인별 건강 적합성을 충분히 상담한 후에 진료 진행 여부를 상호 결정합니다.”",
      },
    ],
    doctorReality: {
      title: "병원은 이미 상상 이상으로 바쁩니다",
      desc: "매일 몰려드는 내외국인 환자 진료부터 임직원 관리까지 쉴 틈이 없는 대표 원장님들.",
      subtitle: "진료만으로도 벅찬데, 수많은 글로벌 채널 운영까지 떠맡을 순 없습니다",
      items: [
        "국내 환자 진료와 시술 집중",
        "대면 상담 및 치료 경과 관찰",
        "병원 인력 운영 및 내부 국내 마케팅 조율",
        "직원 관리 및 병원 원내 오퍼레이션 총괄",
      ],
      question: "여기에 다국어 SNS, 중국 하오토우베이/상세서, 영어 랜딩, 라인·위챗 수시 대응까지 대표님이 직접 다 관리하실 수 있나요?",
      answer: "모든 것을 혼자 짊어지려 하면, 결국 얼마 가지 않아 운영과 소통 채널 모두 멈추게 되고 맙니다.",
    },
    painPoints: {
      title: "대부분의 병원 해외마케팅이 막히는 5대 원인",
      desc: "체계적인 연결 고리(System)와 지속가능성(Fitness)이 없기 때문에 중단되는 경우가 대다수입니다.",
      items: [
        "외국어 번역은 해두었는데, 현지 외국인이 읽기에는 어법과 정서가 몹시 어색하고 굳어 보입니다.",
        "해외 SNS 채널 개설은 멋지게 해두었으나, 전담 인력 한계로 다음 게시물이 꾸준히 올라가지 못합니다.",
        "비용을 들여 광고는 돌렸는데, 클릭만 발생하고 정작 예약을 물어보는 실재적인 문의로 연동되지 않습니다.",
        "드물게 해외 문의가 유입되어도, 담당자가 명확히 기록하지 않거나 어디에 데이터가 보관 중인지 흐지부지합니다.",
        "외국어 응대 능력이 있던 특정 담당 직원이 이직하면 병원의 글로벌 세팅 노하우가 한순간에 소멸합니다.",
      ],
      warningBox: "더 장기적인 위협은 잘못 습관화된 위험 문구들입니다: “절대 안전합니다”, “효과가 영구적이고 확실합니다”, “부작용이 전혀 없습니다”, “무조건 드라마틱하게 개선됩니다” 혹시 병원 공식 랜딩이나 카드뉴스 구석에 이런 문구들이 여전히 걸려 있지는 않습니까?",
    },
    servicesCopy: {
      intro: "해외환자 마케팅은 많이 띄우는 것보다 끝까지 오래 살아남는 튼튼한 온라인 구조를 까는 것이 먼저여야 합니다.",
      subIntro: "저희는 해외환자 유치에 필수적으로 요구되는 다국어 채널 생태계를 끊김없는 완결 구조로 원스톱 세팅해드립니다.",
      consequence: "중간 연결고리가 하나라도 느슨해져 정지하거나 소홀해지면 잠재 고객은 조용히 다른 병원으로 이탈합니다.",
      rejectTitle: "저희 마케팅 철학은 이런 무의미한 방식을 거부합니다 (REJECTS)",
      services: [
        {
          title: "다국어 SNS 콘텐츠 기획 및 주기적 대행",
          desc: "일본어, 중국어, 영어, 동남아 타겟 맞춤으로 병원 브랜드 정체성이 꾸준히 누적 노출되도록 월 50개~100개 채널별 콘텐츠를 빈틈없이 빌드합니다.",
        },
        {
          title: "해외환자 고전환 타겟 랜딩페이지 구조 설계",
          desc: "시술 핵심 설명, 의료진 라이선스 신뢰 지표, 단계별 예약 상담 여정, 병원 입지 도로 교통, 가격 산정 기준 및 주의 강조 요소까지 한 스크린 전환 동선으로 완성도 높게 구축합니다.",
        },
        {
          title: "라인·위챗·왓츠앱 글로벌 문의 채널 통합",
          desc: "메신저 앱과 인콰이어리 폼이 유기적으로 소통하여 고객의 유입이 중도 낙오되지 않고 한 통합 흐름으로 수집되도록 통로 길목을 촘촘히 얹어 줍니다.",
        }
      ],
      rejects: [
        "원어민 정서를 배제한 채 번역기만 돌려 가독성을 저해하는 단순 직역 번역",
        "정보 가치와 설득력은 전무한 채 무조건 비주얼만 번지르르하게 껍데기만 씌운 비전환형 디자인",
        "지속성이 보장되지 않은 채 첫 달 몇 개만 우발적으로 던져놓고 멈춰버리는 SNS 방치형 피드",
        "전환 페이지와 수용 상담 프로세스가 없음에도 예산만 갈아 넣는 영혼 없는 무지성 퍼포먼스 광고 집행",
        "리스크 검증 책임을 전적으로 바쁜 대표 병원장님께 법률 검수 공 넘기듯 미루는 무책임 대행 구조",
      ],
      ourPromise: "저희는 첨단 생성형 AI 모델들을 효율적으로 작동시켜 풍성한 리서치와 기초 초안을 광속으로 가동시키고, 전문 메디컬 도메인 마케터가 2차, 3차로 안전성과 현지 어휘 번안 여부를 매섭게 수정하는 투트랙 검증 시스템으로 움직입니다.",
    },
    crmIntegration: {
      title: "해외환자 문의는 흩어지는 순간 공중 분해됩니다",
      desc: "인스타그램 디엠, LINE, WeChat, WhatsApp, 카카오플러스, 웹 문의폼 등 사방으로 흩어져 수신되는 연락망.",
      channels: [
        "Instagram DM 메신저",
        "LINE 글로벌 메신저",
        "WeChat 대중국 채널",
        "WhatsApp 서구 및 동남아권 유입망",
        "웹사이트 랜딩페이지 문의 신청 폼",
      ],
      solution: "병원의 모든 인바운드 인콰이어리 도달 경로를 분실율 제로 수준에 가깝게 정리 및 추적할 수 있도록, 예약 대기에서 승인까지 일원화되는 심플하고 유용한 CRM 접점 관리 프레임과 매뉴얼을 장착해드립니다.",
    },
    contentEndurance: {
      title: "해외 고객은 결코 오늘 보고 내일 선뜻 결제하지 않습니다",
      desc: "외국계 의료 안심 서비스는 긴 시간에 걸친 반복 노출과 단계적인 안심(Safe) 콘텐츠 공급으로 비로소 성사될 수 있습니다.",
      schedule: [
        "1일 차 : 오해하기 쉬운 시술 절차와 입체적 기작 디테일 번역 설명",
        "2일 차 : 병원 원내 내부 위생 상황 및 하이 테크 장비 리소그래피 노출",
        "3일 차 : 진료 전 대면 정밀 문진 프로세스 및 한국 방문 시 유의 절차 안내",
        "4일 차 : 시술 직후 필수 케어 요령과 조속한 다운타임 회복 팁 전수",
        "5일 차 : 자주 오르내리는 글로벌 질문들에 대한 객관적 FAQ 투명 배포",
      ],
      highlight: "콘텐츠 노출 인프라가 마라톤처럼 튼튼히 누적되어야 단단한 글로벌 신뢰가 함께 축적됩니다.",
      statHighlight: "단순히 월 10개만 올리는 것으로는 한계가 있습니다. 주 12-15회 이상, 다방면 반복 노출을 유지할 수 있는 튼튼한 콘텐츠 기초 자력(체력)만이 결과의 성패를 가릅니다.",
      fullPathDesc: "해외환자 유치는 점진적인 신뢰 비즈니스입니다. 처음 고객이 브랜드를 우연히 스치듯 목격하는 출발 시점부터, 친밀해져서 문의하고 예약 티켓을 무사히 결제하는 안착 지점까지 한 선으로 이어 상호 검증하는 전 여정을 빈틉없이 가라앉힙니다.",
    },
    workStandards: {
      title: "작업은 조잡한 직관이나 감에만 빌붙어 일하지 않습니다",
      intro: "해외 소재 콘텐츠와 가이드를 작성할 때마다 아래 9가지 하드코어 핵심 검사 필터를 거친 뒤 안전하게 송출합니다.",
      standards: [
        { name: "표현 가이드 리스크 검증 (의료법상 불가 표현 사전 필터링)", score: 95 },
        { name: "원어민 기준 번역 자연도 및 뉘앙스 매칭", score: 98 },
        { name: "처음 보는 일반 외국인 고객의 즉각적 이해도 확인", score: 93 },
        { name: "전환 버튼과 챗봇 연결 터치 경로 시각 편의 배치", score: 96 },
        { name: "문의 가이드 및 예약 폼 작성 허들 단계 최소화", score: 94 },
        { name: "인스타그램, 위챗 등 채널별 공식 가로세로 규화 규격 준수", score: 97 },
        { name: "현지 관습과 종교, 정서를 무단 침범하지 않는지 확인", score: 95 },
        { name: "과장 수식어, 극적 문어구 최소화 조정", score: 94 },
        { name: "비교 우위적 비난 소지 단어 제거 순화 작업", score: 96 },
      ],
      warning: "AI 번역기만 나이브하게 전적으로 믿어 사용하면 규정 폭탄으로 소중한 마케팅 채널이 차단될 염려가 높습니다. 반대로 기계적 사람 번역만 고집하면 원고량 속도가 매우 더디고 병원에 청구되는 인건 비율이 지나치게 커집니다.",
      speedEfficiency: "빠르게 골조 기획 초안을 마련하고, 도메인 전문가 메디컬 필터로 안전하고 스마트하게 연착륙시키는 ‘스마트 메커니즘 통합 체계’를 지향합니다.",
    },
    packagesCopy: {
      title: "필요한 진입 장벽 단계부터 유용하게 동참하십시오",
      desc: "의료기관의 현재 확장성과 예산 상태에 맞춰 자유롭게 패키지를 선택 설계하실 수 있도록 지원합니다.",
      packages: [
        {
          name: "Package 01",
          title: "해외환자 마케팅 기초 세팅 패키지",
          price: "초기 진입 진단 구조 수립",
          features: [
            "병원 전체 글로벌 입지 전략 진단",
            "다국어 SNS 기본 유입 구조 레이아웃 기획",
            "이탈 없는 랜딩페이지 문구 프레임워크 설계",
            "의료법 위반 및 주요 위험 표현 1차 안전 체크",
            "LINE·WeChat·WhatsApp 등 원터치 문의 포트 설계",
            "즉각 적용할 수 있는 월간 콘텐츠 주제 가인드라인 30개 배포",
          ],
          cta: "기본기 진단 무료 받기",
          desc: "처음 시작하거나 해외 채널을 새로이 전열 정비하려는 의료원에게 최적화된 기초 도면 기틀을 세웁니다.",
        },
        {
          name: "Package 02",
          title: "월 50~100개 콘텐츠 고밀도 대행 패키지",
          price: "지속가능 정기 운영 체력 수급",
          features: [
            "일본어, 대중국어, 영어 맞춤형 소셜 에셋 정기 수급",
            "병원 주력 시술별 세밀화 시각 카드 제작 및 대본 세팅",
            "체계적인 업로드용 월간 스케줄 캘린더 운용 유지",
            "도합 월 50개-100개 상당의 주기적인 콘텐츠 송출 전담",
            "문의율 유도를 촉진하는 마케팅 특화 CTA 연결 가미",
            "수정 요청 반영 속도 제고 및 정밀 월간 성과 동향 피드백 리포팅",
          ],
          cta: "콘텐츠 운영 정식 의뢰하기",
          desc: "의료 행위와 수술에만 총력 집중할 수 있도록 지속적인 인카운트 글로벌 콘텐츠 체력을 병원에 꾸준히 제공합니다.",
        },
      ],
      materialsTitle: "안내 : 아래 유용한 리소스 자원 데이터들을 협조 정리해주시면 전환 속도가 현격하게 비약합니다",
      materialsDesc: "보유하신 리소스를 메일이나 드라이브로 공유해 주시면, 마케터가 1차 세팅 단계에서 유기적으로 콘텐츠에 버무립니다.",
      materialsList: [
        "시술별 외래 환자 단골 문의사항 및 디테일 자주 묻는 질문집",
        "원내 메디컬 위생 상태 및 인테리어 사진 모음",
        "전문의 이력, 라이선스, 대외 활동 인증 이미지 자료",
        "현재 병원 내부에서 응대 수용 가능한 제2외국어 범주 현황",
        "한국 입국 후 가벼운 병원 내점 시의 상세 워크스루 가이드라인",
        "시술 가격 안내 테이블 책자표 및 주의사항 전수 사초",
      ],
    },
    workflowCopy: {
      title: "그 누구에게도 짐과 번거로운 숙제를 미루지 않습니다",
      desc: "의뢰에서 안착까지 군더더기 없는 5대 단계로 일사천리로 이끕니다.",
      steps: [
        { step: "01", title: "현재 운영 상태 전격 진단", desc: "사용 중이신 SNS, 블로그, 홈페이지 및 도메인을 검수하고, 고객 문의 접점의 현재 낙오 지점을 빈틈없이 포착합니다." },
        { step: "02", title: "위험 표현 및 번역 부조화 검열", desc: "광고 규정을 무단 침탈하고 있는 비규격 문어구를 포착하고, 외국인이 보기에 어색하여 웃어넘길 번역체를 일체 수순 정리합니다." },
        { step: "03", title: "로컬라이즈 고효율 콘텐츠 및 랜딩 구축", desc: "원어민이 마음 깊이 이해하는 안심 전달 텍스트와 핵심 신뢰도 중심의 랜딩 기조를 고안 및 배치합니다." },
        { step: "04", title: "포트폴리오 문의 동선 단일 연동", desc: "LINE, WeChat, WhatsApp, 카카오 등 파편화된 리드를 한 직관적 챗봇 접객 경로로 견고하게 고정 차단 방어합니다." },
        { step: "05", title: "월간 운영 상태 리포트 안착", desc: "매달 발행된 수치와 다음 달 기획 가이드를 정리해 간결 명료하게 원장실 문서로 송부해 드립니다." },
      ],
      footerCallout: "원장님은 수술과 고품격 환자 진료 원내 운영에만 정갈하게 몰입하십시오. 얽히고설킨 모든 글로벌 마케팅 구조는 저희 전문가 조직이 원스톱으로 풀어드리겠습니다.",
    },
    faqs: [
      {
        q: "병원이 해외마케팅을 단 한 번도 해본 적 없이 왕초보인데 바로 동참 가능한가요?",
        a: "전혀 문제없습니다. 오히려 초기 시작 단계일수록 잘못된 어설픈 번역으로 홈페이지를 구축하거나 사후 파손된 채널을 수리하느라 리워드를 들이는 부차 비용을 비약적으로 줄일 수 있어 가장 영리하게 진입하는 골든 타이밍입니다.",
      },
      {
        q: "내부 통역 인력이 아주 부재한데, 일본이나 위챗 등의 소통 대처가 실시간으로 가능한가요?",
        a: "대표님이나 간호 데스크에 가중을 주지 않고 기민하게 맞춤 응대할 수 있는 ‘상황별 다국어 접객 텍스트 세트’와 라우팅 안내 템플릿까지 저희가 다 설계해드리므로 아주 손쉽게 유저 리셉션 대처가 구비됩니다.",
      },
      {
        q: "의료 광고의 복잡해져 가는 특유 법 규정상 진짜 안전성 검수 조율이 완료되는 건가요?",
        a: "효과 보장 단정, 극단적 수식, 전후 조작의 오용 여지가 다분한 어투를 필터링하여 사전 원천 규격화합니다. 법무적 한계 보완이 우려되는 까다로운 쟁점은 전문적 변형 대안 어조 문구를 적극 제시해 드려 사전 리스크를 극명히 축소해 정돈합니당.",
      },
      {
        q: "자료 사진이나 실제 해외환자 유치 증거 지표가 아직 미비해도 랜딩 연동을 할 수 있나요?",
        a: "극도의 초창기 사업자일수록 실적 숫자 자랑보다는, “어떤 정교한 의료 ad-copy 기준표로 작업하는지”, “어떤 리포트 체크리스트를 기용해 검수하는지” 등 '작업 절차 기준'을 HTML 카드나 실물 가이드 샘플과 함께 적극적으로 보여주는 것이 최고급 안심을 만드는 지름길입니다.",
      }
    ],
    contact: {
      label: "SECURE REQUEST",
      title: "지금 우리병원의 해외 환자 전환 동선을 먼저 점검하십시오",
      desc: "공식 SNS 채널, 무의미하게 개설된 인스타그램 아이디, 수동식 안내 등 어디에서 외국인 환자가 낙심하여 이탈 중인지 정밀 스크리닝해 드리겠습니다.",
      email: "귀하의 이메일 연락처",
      placeholder: "name@hospital.com",
      button: "1차 전환 동선 진단 요청하기",
      note: "방대한 기존 자료가 전무해도 무방합니다. 현재 활용하고 있는 가벼운 홈페이지 링크나 인스타그램 주소 한 개만 기입해 두셔도 1차 기초 진단을 정식 수립하여 송부해 드립니다.",
    },
  },
  en: {
    nav: {
      home: "Home",
      proof: "Proof",
      risk: "Risk",
      services: "Services",
      process: "Process",
      packages: "Packages",
      faq: "FAQ",
      contact: "Contact",
      cta: "Free Audit",
    },
    brand: {
      name: "TRUSTA",
      sub: "GLOBAL MEDICAL MARKETING OS",
    },
    hero: {
      badge: "Global Patient Growth Team",
      line1: "Global patient growth",
      line2: "without guesswork",
      desc: "Engage Japanese, Chinese, and Southeast Asian patients through high-conversion landing pages, unified messenger channels, persistent social content, and medical ad copy compliance screening.",
      primary: "Request Free Audit",
      secondary: "Global Patients Marketing OS",
      stat1: "50-100",
      stat1Label: "Monthly Social Assets",
      stat2: "3-Step Filter",
      stat2Label: "AI draft + Expert review",
      stat3: "Leak-Proof",
      stat3Label: "SNS -> Page -> Live CRM route",
    },
    philosophy: {
      title: "Global patient marketing is not just beautiful translation",
      desc: "Simply using a high-class translation does not capture professional trust nor guarantees compliance with medical advertising laws.",
      elements: [
        "Wording natural and intuitive for localized eyes",
        "Safe phrasing that ad engines will not flag or block",
        "Structures pre-screened for medical ad regulatory risks",
        "Streamlined inquiries straight into secure conversion channels",
      ],
    },
    differentiation: {
      title: "We are built different from direct translation agencies",
      desc: "Instead of just generating impressions, we build continuous loops that funnel modern prospects into real clinical appointments.",
      cards: [
        "We are different from direct dictionary translators",
        "We are not an automated bot that uploads copy-paste daily spam on Instagram",
        "We are not a temporary landing designer who builds beautiful websites with dead CTA buttons",
      ],
      highlight: "We systematically bind high-converting multilingual content with live LINE·WeChat·WhatsApp connection channels in one go, so that patients believe and act.",
    },
    copyRisk: {
      title: "The biggest danger in global medical growth is",
      desc: "Not pausing marketing, but publishing dangerous, non-compliant, or over-promised claims that can terminate clinic licenses.",
      intro: "Clinics must respect local health laws and ad platform compliance requirements to escape prompt account termination.",
      points: [
        "Over-promising or guaranteed positive medical results",
        "Uncertified extreme before & after photos",
        "Inappropriate usage of unverified patient review content",
        "Wording that claims treatment is completely perfect",
        "Unnatural translation phrasing that looks robotic",
      ],
      consequences: "A single wrong claim like this leads directly to advertising rejection, post deletions, profile bans, and massive brand loss.",
      titleBeforeAfter: "Good medical copywriting is never about glowing hype",
      descBeforeAfter: "Our core strength is translating risky or illegal claims into safe, highly engaging informational statements that secure both approval and patients' faith.",
    },
    riskPairs: [
      {
        level: "RISK WORDING (RED/BEFORE)",
        tone: "Ad Reject #1: Outcome Guarantee",
        title: "Before: Perfect results in one visit",
        before: "“Guaranteed perfect results with only one treatment.”",
        after: "“Results may vary depending on individual skin and tissue conditions. We invite you for an in-person diagnostic test to recommend a customized medical path.”",
      },
      {
        level: "CAUTION WORDING (YELLOW/BEFORE)",
        tone: "Underplaying clinical side effects",
        title: "Before: No risk or pain whatsoever",
        before: "“A perfectly safe procedure with absolutely no side effects.”",
        after: "“Minor swelling or temporary discomfort can occur depending on individual recovery. We decide suitability after analyzing clinical pre-checks.”",
      },
    ],
    doctorReality: {
      title: "Doctors are already extremely busy",
      desc: "Managing existing consultation queues, surgery rooms, and local clinic operations leaves zero free hours.",
      subtitle: "You cannot administer surgeries and simultaneously run active social media accounts in Japanese and Chinese",
      items: [
        "Treating local and active foreign in-patients",
        "Conducting surgeries and follow-up clinical checks",
        "Recruiting clinic team members and reviewing general overheads",
        "Overseeing local advertising channels and domestic hospital operations",
      ],
      question: "Can you realistically maintain active LINE channels, translate brochures into Chinese, and keep up with ad laws?",
      answer: "When doctors attempt to wear all these hats, content quality breaks down and patient response channels go completely cold.",
    },
    painPoints: {
      title: "5 Core Reasons why global clinic marketing stalls",
      desc: "Most approaches lack systemic continuity and organic compliance setups, leading to quick abandonment.",
      items: [
        "English, Japanese or Chinese translation feels awkward, cold, and literal to native eyes.",
        "Beautiful social accounts are initially created, but stop publishing due to lack of dedicate writers.",
        "Paid ads bring clicks, but never convert into real clinical booking queries due to broken conversion flows.",
        "When inquiries arrive, they are messy, untracked, and easily lost across multiple raw inboxes.",
        "When a bilingual nurse or clinical coordinator leaves, all global marketing and follow-up data vanishes with them.",
      ],
      warningBox: "The deeper risk is repetitive risky copywriting: “Absolutely safe”, “Guaranteed outcome”, “No side-effects”, “Instant massive improvement”. Are these dangerous absolute claims still written on your landing pages?",
    },
    servicesCopy: {
      intro: "Instead of wasting budget on instant exposure, clinics must establish highly resilient compliance infrastructures that stand the test of time.",
      subIntro: "We set up an uninterrupted multi-channel patient acquisition ecosystem from content strategy to live CRM entry.",
      consequence: "If any single piece of the chain breaks, modern patients quietly exit and choose competitors instead.",
      rejectTitle: "We strongly refuse these unhelpful methods (REJECTS)",
      services: [
        {
          title: "Multilingual SNS content planning & full distribution",
          desc: "Targeting Japanese, Chinese, English, and Southeast Asian demographics. We plan and build 50 to 100 on-brand, high-quality assets per month to maintain clinical authority.",
        },
        {
          title: "High-convert clinic landing page conversion framework",
          desc: "We write treatment guidelines, clinical certifications, price transparency disclosures, location access, and secure inquiry flows into a clean layout.",
        },
        {
          title: "Integrated LINE, WeChat & WhatsApp conversion routes",
          desc: "Ensure prospects from social feeds land directly inside interactive, unified chat routes without leaking midway.",
        }
      ],
      rejects: [
        "Direct literal dictionary translation that eliminates clinical credibility",
        "Visually pleasing but completely dead interfaces with no functional CTA buttons",
        "Inconsistent social assets that are abandoned after a couple of posts",
        "Wasting paid ad budgets on raw traffic when no conversion CRM processes are prepared",
        "Shifting all compliance liabilities onto the busy clinical director or medical staff",
      ],
      ourPromise: "We use state-of-the-art AI systems for fast localized research and content drafting, followed by strict multi-step human review by healthcare marketing experts to eliminate all awkwardness and compliance risks.",
    },
    crmIntegration: {
      title: "Broken inquiry routes lead to lost patients",
      desc: "When prospects are scattered across direct messages, LINE, WeChat, WhatsApp, and email, clinical leads disappear.",
      channels: [
        "Instagram business DM route",
        "LINE global patient channel",
        "WeChat Chinese patient funnel",
        "WhatsApp regional inquiry channel",
        "Official landing page form portals",
      ],
      solution: "We establish a highly intuitive CRM lead management workflow and templates that aggregate every patient contact point, minimizing response leakage.",
    },
    contentEndurance: {
      title: "International patients do not buy clinic services instantly",
      desc: "Global medical decisions demand repeated trust exposure and safe, informational, compliant steps over time.",
      schedule: [
        "Day 1: Detailed workflow explanation of complex treatment steps",
        "Day 2: Showcasing hospital hygiene measures and premium clinical machinery",
        "Day 3: Preparing for preoperative medical checks and traveling to Korea",
        "Day 4: Precise postoperative care, safety instructions, and recovery support",
        "Day 5: Releasing fully compliant FAQs regarding safety and transparent pricing",
      ],
      highlight: "Repetitive, high-value visual proof builds the clinic’s long-term global authority.",
      statHighlight: "Posting 10 times a month is barely visible. Maintaining 50-100 high-value compliant posts across major global channels is the endurance baseline for modern conversion.",
      fullPathDesc: "Global patient procurement is an endurance run. We design every step from the first touchpoint, content build, inquiry form, to the final appointment confirmation in one unified pathway.",
    },
    workStandards: {
      title: "We operate on cold data and proven compliance metrics",
      intro: "Every piece of copy and design goes through our strict 9-layer compliance and quality review system.",
      standards: [
        { name: "Wording regulatory risk filter (Medical law validation)", score: 95 },
        { name: "Native naturalness and localized context matchmaking", score: 98 },
        { name: "Immediately clear clarity for first-time website visitors", score: 93 },
        { name: "Conversion CTA buttons positioned optimally for mobile touch", score: 96 },
        { name: "User sign-up steps and forms minimized for lower friction", score: 94 },
        { name: "Platform layout compliance (Dimensions, formats, resolution limits)", score: 97 },
        { name: "Cultural adaptation ensuring zero offense to religious/local customs", score: 95 },
        { name: "Over-hyped adjective removal and safety phrase replacements", score: 94 },
        { name: "Removal of aggressive competitive claims and negative reviews", score: 96 },
      ],
      warning: "Relying purely on raw machine translation risks instant channel suspensions. Conversely, relying strictly on traditional manual translation is slow and costs clinics excessive overhead budgets.",
      speedEfficiency: "Our hybrid execution engine merges rapid AI drafting with human editing, delivering both unmatched speed and pristine regulatory safety.",
    },
    packagesCopy: {
      title: "Choose the package tailored to your clinic's expansion scale",
      desc: "Select the starting step depending on your database volume and target budget.",
      packages: [
        {
          name: "Package 01",
          title: "Global Patient Setup Package",
          price: "Foundation Diagnostic Build",
          features: [
            "Complete clinic global branding strategy audit",
            "Multilingual social growth layout blueprint",
            "High-converting landing page compliance copywriting",
            "Medical law warning pre-check and copy modifications",
            "One-touch LINE, WeChat, WhatsApp channel config",
            "30 customized monthly content topic templates",
          ],
          cta: "Request Free Foundation Audit",
          desc: "Perfect for clinics launching global channels or restructuring non-performing pages from scratch.",
        },
        {
          name: "Package 02",
          title: "50-100 Monthly Content Operations Package",
          price: "Full-scale Monthly Retainer",
          features: [
            "Custom-designed social posts for JP, CN, and EN audiences",
            "Visual cards and scripts optimized per clinical treatment type",
            "Strategic content calendar built and adjusted in real time",
            "Guaranteed delivery of 50 to 100 specialized posts per month",
            "Conversion-oriented CTA button copywriting",
            "Transparent monthly performance report and adjustments",
          ],
          cta: "Request Full Operations Service",
          desc: "Focus entirely on treatments and let our expert healthcare content operating system power your channels.",
        },
      ],
      materialsTitle: "Guideline: Preparing these details accelerates global patient acquisition dramatically",
      materialsDesc: "If you have any of these digital resources, share them on our cloud drive so managers can naturally weave them into the copy.",
      materialsList: [
        "Frequently asked questions from global clinical inquiries",
        "High-resolution photos of clinical rooms and equipment",
        "Clinical doctors' profile bio, licenses, and achievements",
        "List of available foreign languages spoken by nurses or doctors",
        "Detailed transport instruction card from airports to clinic entries",
        "Pricing breakdown booklets and required post-op guidelines",
      ],
    },
    workflowCopy: {
      title: "Zero homework left on busy doctors' desks",
      desc: "An organized 5-stage workflow that launches your global acquisition system seamlessly.",
      steps: [
        { step: "01", title: "Diagnostic audit of current assets", desc: "We review active profiles, landing pages, and locate exactly where international inquiries are currently leaking." },
        { step: "02", title: "Risky copy and translation screening", desc: "We find any non-compliant claims and replace robotic translations with fluent native sentences." },
        { step: "03", title: "Multilingual high-conversion setup", desc: "We build intuitive landing pages focusing on trust metrics and native-friendly formatting." },
        { step: "04", title: "One-touch messaging integration", desc: "We connect LINE, WeChat, and WhatsApp into clear routes to keep potential patients from slipping away." },
        { step: "05", title: "Monthly analytics reporting", desc: "We track performance metrics and deliver transparent adjustments straight to your office inbox." },
      ],
      footerCallout: "Focus entirely on surgeries and professional healthcare delivery. We take care of the entire global content operating system.",
    },
    faqs: [
      {
        q: "Can a clinic begin even if you have zero global marketing experience?",
        a: "Absolutely. Starting correctly from day one avoids the heavy cost of rebuilding non-compliant pages and repairing suspended accounts left by cheap direct translation agencies.",
      },
      {
        q: "What if we have no in-house translators for WeChat or LINE requests?",
        a: "We design structured bilingual templates and inquiry scripts for your reception desk, helping your team handle initial intake without stress.",
      },
      {
        q: "How safe is medical compliance under your ad screening?",
        a: "We proactively flag outcome guarantees, exaggerated results, and uncertified claims, replacing them with compliant informational alternatives. This minimizes regulatory risks.",
      },
      {
        q: "Can we build a high-converting site without big clinical statistics yet?",
        a: "Yes. Early-stage services can build premium trust by publishing their precise compliance standards, review checklists, and detailed process workflows instead.",
      }
    ],
    contact: {
      label: "SECURE REQUEST",
      title: "Audit your global patient flow now",
      desc: "Find out where prospective patients drop out in your active social accounts, landing pages, or inquiry processes.",
      email: "Your Primary Work Email",
      placeholder: "name@hospital.com",
      button: "Request Free 1st Conversion Audit",
      note: "No extensive files are required. A simple link to your current workspace or homepage is enough for us to compile your first diagnostic report.",
    },
  },
};
